apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 20s
  sourceRef:
    kind: GitRepository
    name: flux-repo
  path: ./apps
  prune: true
  wait: true
  timeout: 5m0s